import type { Metadata } from 'next';
import './globals.css';
import { fonts } from './fonts';
import { Providers } from './providers';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.inter.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
